name: Deploy Backend to ECS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-ecs.yml'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 425687053209.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: clubapp-backend
  ECS_SERVICE: clubapp-backend-service
  ECS_CLUSTER: clubapp-dev-cluster
  ECS_TASK_DEFINITION: clubapp-backend-task

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::425687053209:role/github-actions-apprunner
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Push image to ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Update ECS task definition
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          # Just use the :latest tag directly in task definition
          sed -i "s|BACKEND_IMAGE_URI|${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest|g" task-definition.json
          aws ecs register-task-definition --cli-input-json file://task-definition.json --region ${{ env.AWS_REGION }}

      - name: Deploy to ECS
        env:
          TASK_DEFINITION: clubapp-backend-task
        run: |
          cd backend
          aws ecs register-task-definition --cli-input-json file://task-definition.json --region $AWS_REGION
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION
